name: News&Crypto 2.0

options:
  defaultConfig: Release
  groupSortPosition: bottom
  
configs:
  # Дев аккаунт
  Debug: debug # Использовать для компиляции на симуляторах и устройствах
  Release: release # Использовать для компиляции на симуляторах и устройствах
  
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    minorVersion: 7.0.0
  # UILib:
  #   path: ./UILib

  
options:
  # preGenCommand:
  #   rm -rf ~/Library/Developer/Xcode/DerivedData
  #   rm -rf ./Pods
  postGenCommand: pod install

targets:

  News&Crypto 2.0:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    name: News&Crypto 2.0
    sources:
        - ./News&Crypto 2.0
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: "News&Crypto 2.0-Bridging-Header.h"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        CLANG_ENABLE_MODULES: YES
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        CODE_SIGN_STYLE: Manual
        CURRENT_PROJECT_VERSION: 1
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        GCC_NO_COMMON_BLOCKS: NO
        GCC_WARN_INHIBIT_ALL_WARNINGS: NO
        LLVM_LTO: NO
        MARKETING_VERSION: 1.0.0
        SWIFT_VERSION: 5.8
        TARGETED_DEVICE_FAMILY: 1,2
        iOS_DEPLOYMENT_TARGET: 14.0
        OTHER_CODE_SIGN_FLAGS: --timestamp
        DEFINES_MODULE: YES
        ENABLE_BITCODE: NO
    dependencies:
      - package: Kingfisher
      # - package: UILib
      #   embed: true
